import json
from pprint import pprint

import requests


class GlobalData:
    # ATPHost = 'http://172.18.6.52:8000'
    ATPHost = 'http://172.18.169.20:8000'
    # ATPHost = 'http://0.0.0.0:8000'
    header = {'accept': 'application/json', 'Content-Type': 'application/json'}

    # @classmethod
    # def get_global_data(cls, env=None, system_type=None):
    #     atp_url = cls.ATPHost + "/global_data/get_all_global_data_by_env_and_system_type"
    #     params = {"env": env,
    #               "system_type": system_type}
    #     response = requests.get(atp_url, headers=cls.header, params=params)
    #     return response.json()

    Common_data = {
        'CANCEL_ALL_ORDER_URL': {'Delivery': '/api/v1/contract_cancelall',
                                 'Swap': '/swap-api/v1/swap_cancelall',
                                 'LinearSwap': '/linear-swap-api/v1/swap_cancelall'},
        'SWITCH_LEVER_URL': {'Delivery': '/api/v1/contract_switch_lever_rate',
                             'Swap': '/swap-api/v1/swap_switch_lever_rate',
                             'LinearSwap': '/linear-swap-api/v1/swap_switch_lever_rate'},
        'DEFAULT_SYMBOL': {'Delivery': 'BTC',
                           'Swap': 'BTC',
                           'LinearSwap': 'BTC'},
        'DEFAULT_CONTRACT_CODE': {'Delivery': 'BTC_CW',
                                  'Swap': 'ETH-USD',
                                  'LinearSwap': 'BTC-USDT'},
        'CANCEL_ALL_TRACK_ORDER_URL': {'Delivery': '/api/v1/contract_track_cancelall',
                                       'Swap': '/swap-api/v1/swap_track_cancelall',
                                       'LinearSwap': '/linear-swap-api/v1/swap_track_cancelall'},
        'CANCEL_ALL_TPSL_ORDER_URL': {'Delivery': '/api/v1/contract_tpsl_cancelall',
                                      'Swap': '/swap-api/v1/swap_tpsl_cancelall',
                                      'LinearSwap': '/linear-swap-api/v1/swap_tpsl_cancelall'},
        'CANCEL_ALL_TRIGGER_ORDER_URL': {'Delivery': '/api/v1/contract_trigger_cancelall',
                                         'Swap': '/swap-api/v1/swap_trigger_cancelall',
                                         'LinearSwap': '/linear-swap-api/v1/swap_trigger_cancelall'},
        'POSITION_INFO_URL': {'Delivery': '/api/v1/contract_position_info',
                              'Swap': '/swap-api/v1/swap_position_info',
                              'LinearSwap': '/linear-swap-api/v1/swap_position_info'},
        'CONTRACT_ORDER': {'Delivery': '/api/v1/contract_order',
                           'Swap': '/swap-api/v1/swap_order',
                           'LinearSwap': '/linear-swap-api/v1/swap_order'},
        'CONTRACT_INFO_URL': {'Delivery': '/api/v1/contract_contract_info',
                              'Swap': '/swap-api/v1/swap_contract_info',
                              'LinearSwap': '/linear-swap-api/v1/swap_contract_info'},
        'MARKET_DEPTH_URL': {'Delivery': '/market/depth',
                             'Swap': '/swap-ex/market/depth',
                             'LinearSwap': '/linear-swap-ex/market/depth'}
    }
    config_data = {
        'Test5': {
            'base_url': 'http://test-5.dm.huobiapps.com',
            'AT_DEFAULT_ACCESS_KEY': 'e6be9ab2-bdb043a0-fdfa7002-mn8ikls4qg',
            'AT_DEFAULT_SECRET_KEY': '07c2a926-032ce8f5-0904eb98-b9d1c',
            'AT_DEFAULT_HBSESSION': 'f0d7104f-0693-492d-b7d1-e3f416ff2217',
            'MULANURL': 'http://mulan-asset.test-5.huobiapps.com',
            'COMMON_ACCESS_KEY': 'dc84e941-uymylwhfeg-91d62498-e1a65',
            'COMMON_SECRET_KEY': '4f211923-cb80c3ad-cb36347f-3fb50',
            'ATP_SERVER_ACCESS_KEY': '5c2bbc46-bg2hyw2dfg-f791689b-e5246',
            'ATP_SERVER_SECRET_KEY': '8b894e8e-e857f455-41625958-ccc60',
            'WSURL': 'ws://test-5.dm.huobiapps.com',
            'REDIS_CONF': {"redis6379": {"host": "172.18.168.247", "port": 6379, "pwd": "rNEAz9uFwHoymy5i"},
                           "redis7000": {"host": "172.18.171.61", "port": 7000, "pwd": ""},
                           "redis7001": {"host": "172.18.171.61", "port": 7001, "pwd": ""},
                           "redis7002": {"host": "172.18.171.61", "port": 7002, "pwd": ""},
                           "redis6380": {"host": "172.18.168.247", "port": 6380, "pwd": "rNEAz9uFwHoymy5i"}},
            'MYSQL_CONF': {'Delivery': {"host": "172.18.170.134", "port": 3306, "userName": "contract",
                                        "passwd": "hQqXR1S#2#bG#6G"},
                           'Swap': '',
                           'LinearSwap': ''
                           },

            'USERINFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
            'MGT_INFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''}
        }.update(Common_data),
        'Test6': {
            'base_url': 'http://test5-contract-hw.dm.huobiapps.com',
            'AT_DEFAULT_ACCESS_KEY': 'bgrdawsdsd-e89a29f8-8babcd38-b4500',
            'AT_DEFAULT_SECRET_KEY': '40cd9ab8-4c8df2c8-970b689f-36d31',
            'AT_DEFAULT_HBSESSION': 'a79392cc-e3db-428f-948b-b3b11d0b1887',
            'MULANURL': 'http://mulan-asset.test-5.huobiapps.com',
            'COMMON_SECRET_KEY': '7688c52d-3100c557-bd84ccff-e17b8',
            'COMMON_ACCESS_KEY': '0110f807-1qdmpe4rty-573506a0-951b8',
            'ATP_SERVER_ACCESS_KEY': '6963f585-aa1c4a98-mn8ikls4qg-6ab49',
            'ATP_SERVER_SECRET_KEY': '974767b7-a320ec58-0ab9bd1a-de0a8',
            'CANCEL_ALL_ORDER_URL': {'Delivery': '/api/v1/contract_cancelall',
                                     'Swap': '/swap-api/v1/swap_cancelall',
                                     'LinearSwap': '/linear-swap-api/v1/swap_cancelall'},
            'SWITCH_LEVER_URL': {'Delivery': '/api/v1/contract_switch_lever_rate',
                                 'Swap': '/swap-api/v1/swap_switch_lever_rate',
                                 'LinearSwap': '/linear-swap-api/v1/swap_switch_lever_rate'},
            'DEFAULT_SYMBOL': {'Delivery': 'BTC',
                               'Swap': 'BTC',
                               'LinearSwap': 'BTC'},
            'DEFAULT_CONTRACT_CODE': {'Delivery': 'BTC_CW',
                                      'Swap': 'ETH-USD',
                                      'LinearSwap': 'BTC-USDT'},
            'CANCEL_ALL_TRACK_ORDER_URL': {'Delivery': '/api/v1/contract_track_cancelall',
                                           'Swap': '/swap-api/v1/swap_track_cancelall',
                                           'LinearSwap': '/linear-swap-api/v1/swap_track_cancelall'},
            'CANCEL_ALL_TPSL_ORDER_URL': {'Delivery': '/api/v1/contract_tpsl_cancelall',
                                          'Swap': '/swap-api/v1/swap_tpsl_cancelall',
                                          'LinearSwap': '/linear-swap-api/v1/swap_tpsl_cancelall'},
            'CANCEL_ALL_TRIGGER_ORDER_URL': {'Delivery': '/api/v1/contract_trigger_cancelall',
                                             'Swap': '/swap-api/v1/swap_trigger_cancelall',
                                             'LinearSwap': '/linear-swap-api/v1/swap_trigger_cancelall'},
            'POSITION_INFO_URL': {'Delivery': '/api/v1/contract_position_info',
                                  'Swap': '/swap-api/v1/swap_position_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_position_info'},
            'CONTRACT_ORDER': {'Delivery': '/api/v1/contract_order',
                               'Swap': '/swap-api/v1/swap_order',
                               'LinearSwap': '/linear-swap-api/v1/swap_order'},
            'CONTRACT_INFO_URL': {'Delivery': '/api/v1/contract_contract_info',
                                  'Swap': '/swap-api/v1/swap_contract_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_contract_info'},
            'MARKET_DEPTH_URL': {'Delivery': '/market/depth',
                                 'Swap': '/swap-ex/market/depth',
                                 'LinearSwap': '/linear-swap-ex/market/depth'},
            'WSURL': 'ws://test5-contract-hw.dm.huobiapps.com',
            'REDIS_CONF': {'Delivery': {"redis6379": {"host": "172.18.6.119", "port": 6379, "pwd": "rNEAz9uFwHoymy5i"},
                                        "redis7000": {"host": "172.18.6.119", "port": 7000, "pwd": ""},
                                        "redis7001": {"host": "172.18.6.119", "port": 7001, "pwd": ""},
                                        "redis7002": {"host": "172.18.6.119", "port": 7002, "pwd": ""},
                                        "redis6380": {"host": "172.18.6.119", "port": 6380, "pwd": "rNEAz9uFwHoymy5i"}},
                           'Swap': '',
                           'LinearSwap': ''},
            'MQ_INFO': {'Delivery': '',
                        'Swap': '',
                        'LinearSwap': ''},
            'MYSQL_CONF': {'Delivery': '',
                           'Swap': '',
                           'LinearSwap': ''},
            'USERINFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
            'MGT_INFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''}
        },
        'Test20': {
            'base_url': 'http://test20-delivery-ingress.bitfanssim.com',
            'AT_DEFAULT_ACCESS_KEY': '1edc67b5-82f7623d-cc4e3642-dab4c45e6f',  # 87b8cd7a-94624d05-7yngd7gh5g-02d65
            'AT_DEFAULT_SECRET_KEY': 'aecfe0fe-a5b48bce-1413cda5-288af',  # ec21c813-66181483-80fb9396-308fe
            # 'AT_DEFAULT_ACCESS_KEY': '87b8cd7a-94624d05-7yngd7gh5g-02d65',  # 87b8cd7a-94624d05-7yngd7gh5g-02d65
            # 'AT_DEFAULT_SECRET_KEY': 'ec21c813-66181483-80fb9396-308fe',  # ec21c813-66181483-80fb9396-308fe

            'AT_DEFAULT_HBSESSION': 'fbd9d39d-5c83-4d90-b23c-9ebe41a4d735',
            'MULANURL': '',
            'COMMON_SECRET_KEY': 'a82b8ca8-bvrge3rf7j-d0764aab-37783',
            'COMMON_ACCESS_KEY': '04aa6237-c022cbfc-ff75104f-85934',
            'ATP_SERVER_ACCESS_KEY': '3d2xc4v5bu-a2ce2c6d-1f8dc45d-d13b7',
            'ATP_SERVER_SECRET_KEY': 'cc017df2-a0bf652d-d350abf9-1019d',
            'CANCEL_ALL_ORDER_URL': {'Delivery': '/api/v1/contract_cancelall',
                                     'Swap': '/swap-api/v1/swap_cancelall',
                                     'LinearSwap': '/linear-swap-api/v1/swap_cancelall'},
            'SWITCH_LEVER_URL': {'Delivery': '/api/v1/contract_switch_lever_rate',
                                 'Swap': '/swap-api/v1/swap_switch_lever_rate',
                                 'LinearSwap': '/linear-swap-api/v1/swap_switch_lever_rate'},
            'DEFAULT_SYMBOL': {'Delivery': 'ETC',
                               'Swap': 'BTC',
                               'LinearSwap': 'BTC'},
            'DEFAULT_CONTRACT_CODE': {'Delivery': 'ETC_CW',
                                      'Swap': 'ETH-USD',
                                      'LinearSwap': 'BTC-USDT'},
            'CANCEL_ALL_TRACK_ORDER_URL': {'Delivery': '/api/v1/contract_track_cancelall',
                                           'Swap': '/swap-api/v1/swap_track_cancelall',
                                           'LinearSwap': '/linear-swap-api/v1/swap_track_cancelall'},
            'CANCEL_ALL_TPSL_ORDER_URL': {'Delivery': '/api/v1/contract_tpsl_cancelall',
                                          'Swap': '/swap-api/v1/swap_tpsl_cancelall',
                                          'LinearSwap': '/linear-swap-api/v1/swap_tpsl_cancelall'},
            'CANCEL_ALL_TRIGGER_ORDER_URL': {'Delivery': '/api/v1/contract_trigger_cancelall',
                                             'Swap': '/swap-api/v1/swap_trigger_cancelall',
                                             'LinearSwap': '/linear-swap-api/v1/swap_trigger_cancelall'},
            'POSITION_INFO_URL': {'Delivery': '/api/v1/contract_position_info',
                                  'Swap': '/swap-api/v1/swap_position_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_position_info'},
            'CONTRACT_ORDER': {'Delivery': '/api/v1/contract_order',
                               'Swap': '/swap-api/v1/swap_order',
                               'LinearSwap': '/linear-swap-api/v1/swap_order'},
            'CONTRACT_INFO_URL': {'Delivery': '/api/v1/contract_contract_info',
                                  'Swap': '/swap-api/v1/swap_contract_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_contract_info'},
            'MARKET_DEPTH_URL': {'Delivery': '/market/depth',
                                 'Swap': '/swap-ex/market/depth',
                                 'LinearSwap': '/linear-swap-ex/market/depth'},
            'WSURL': 'ws://test-20.dm.huobiapps.com',
            'REDIS_CONF': {'Delivery': {"redis6379": {"host": "172.18.6.119", "port": 6379, "pwd": "rNEAz9uFwHoymy5i"},
                                        "redis7000": {"host": "172.18.6.119", "port": 7000, "pwd": ""},
                                        "redis7001": {"host": "172.18.6.119", "port": 7001, "pwd": ""},
                                        "redis7002": {"host": "172.18.6.119", "port": 7002, "pwd": ""},
                                        "redis6380": {"host": "172.18.6.119", "port": 6380, "pwd": "rNEAz9uFwHoymy5i"}},
                           'Swap': '',
                           'LinearSwap': ''},
            'MQ_INFO': {'Delivery': '',
                        'Swap': '',
                        'LinearSwap': ''},
            'MYSQL_CONF': {'Delivery': '',
                           'Swap': '',
                           'LinearSwap': ''},
            'USERINFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
            'MGT_INFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''}
        },
        'NHW_Test6': {
            'base_url': 'http://test6-api-hw.dm.huobiapps.com',
            'AT_DEFAULT_ACCESS_KEY': '49318fc1-3ddfe94d-ca130d53-vqgdf4gsga',
            'AT_DEFAULT_SECRET_KEY': 'eb2825c0-b35d381f-405082da-58414',
            'AT_DEFAULT_HBSESSION': 'xxxxxx',
            'MULANURL': '',
            'COMMON_ACCESS_KEY': '34328ffc-f1928739-5dae86a6-dqnh6tvdf3',
            'COMMON_SECRET_KEY': 'fc606cae-d0be94c1-cfb4a47d-ff722',
            'ATP_SERVER_ACCESS_KEY': '598287a3-ca762c01-qz5c4v5b6n-e7def',
            'ATP_SERVER_SECRET_KEY': '01fc1c60-6726f9a4-93f77d7e-83db5',
            'CANCEL_ALL_ORDER_URL': {'Delivery': '/api/v1/contract_cancelall',
                                     'Swap': '/swap-api/v1/swap_cancelall',
                                     'LinearSwap': '/linear-swap-api/v1/swap_cancelall'},
            'SWITCH_LEVER_URL': {'Delivery': '/api/v1/contract_switch_lever_rate',
                                 'Swap': '/swap-api/v1/swap_switch_lever_rate',
                                 'LinearSwap': '/linear-swap-api/v1/swap_switch_lever_rate'},
            'DEFAULT_SYMBOL': {'Delivery': 'BTC',
                               'Swap': 'BTC',
                               'LinearSwap': 'BTC'},
            'DEFAULT_CONTRACT_CODE': {'Delivery': 'BTC_CW',
                                      'Swap': 'ETH-USD',
                                      'LinearSwap': 'BTC-USDT'},
            'CANCEL_ALL_TRACK_ORDER_URL': {'Delivery': '/api/v1/contract_track_cancelall',
                                           'Swap': '/swap-api/v1/swap_track_cancelall',
                                           'LinearSwap': '/linear-swap-api/v1/swap_track_cancelall'},
            'CANCEL_ALL_TPSL_ORDER_URL': {'Delivery': '/api/v1/contract_tpsl_cancelall',
                                          'Swap': '/swap-api/v1/swap_tpsl_cancelall',
                                          'LinearSwap': '/linear-swap-api/v1/swap_tpsl_cancelall'},
            'CANCEL_ALL_TRIGGER_ORDER_URL': {'Delivery': '/api/v1/contract_trigger_cancelall',
                                             'Swap': '/swap-api/v1/swap_trigger_cancelall',
                                             'LinearSwap': '/linear-swap-api/v1/swap_trigger_cancelall'},
            'POSITION_INFO_URL': {'Delivery': '/api/v1/contract_position_info',
                                  'Swap': '/swap-api/v1/swap_position_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_position_info'},
            'CONTRACT_ORDER': {'Delivery': '/api/v1/contract_order',
                               'Swap': '/swap-api/v1/swap_order',
                               'LinearSwap': '/linear-swap-api/v1/swap_order'},
            'CONTRACT_INFO_URL': {'Delivery': '/api/v1/contract_contract_info',
                                  'Swap': '/swap-api/v1/swap_contract_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_contract_info'},
            'MARKET_DEPTH_URL': {'Delivery': '/market/depth',
                                 'Swap': '/swap-ex/market/depth',
                                 'LinearSwap': '/linear-swap-ex/market/depth'},
            'WSURL': 'ws://test-20.dm.huobiapps.com',
            'REDIS_CONF': {'Delivery': {"redis6379": {"host": "172.18.6.119", "port": 6379, "pwd": "rNEAz9uFwHoymy5i"},
                                        "redis7000": {"host": "172.18.6.119", "port": 7000, "pwd": ""},
                                        "redis7001": {"host": "172.18.6.119", "port": 7001, "pwd": ""},
                                        "redis7002": {"host": "172.18.6.119", "port": 7002, "pwd": ""},
                                        "redis6380": {"host": "172.18.6.119", "port": 6380, "pwd": "rNEAz9uFwHoymy5i"}},
                           'Swap': '',
                           'LinearSwap': ''},
            'MQ_INFO': {'Delivery': '',
                        'Swap': '',
                        'LinearSwap': ''},
            'MYSQL_CONF': {'Delivery': '',
                           'Swap': '',
                           'LinearSwap': ''},
            'USERINFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
            'MGT_INFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
        },
        'NHW_Test20': {
            'base_url': 'http://newtest20-contract-hw.dm.huobiapps.com/',
            'AT_DEFAULT_ACCESS_KEY': 'bgrveg5tmn-2d28ef22-fa62b540-3b7ca',
            'AT_DEFAULT_SECRET_KEY': '2c88d131-32a26199-3278d60e-1c4da',
            'AT_DEFAULT_HBSESSION': '',
            'MULANURL': '',
            'COMMON_SECRET_KEY': 'accc747a-ae4c26db-a5ec3a3b-bvrge3rf7j',
            'COMMON_ACCESS_KEY': '0d96a933-081292f6-8666e4b5-4ee9d',
            'ATP_SERVER_ACCESS_KEY': '384f5dd2-dbuqg6hkte-6cc6f1ca-2751b',
            'ATP_SERVER_SECRET_KEY': 'e15eed1e-a5edb5d5-2fb8d3b3-62a03',
            'CANCEL_ALL_ORDER_URL': {'Delivery': '/api/v1/contract_cancelall',
                                     'Swap': '/swap-api/v1/swap_cancelall',
                                     'LinearSwap': '/linear-swap-api/v1/swap_cancelall'},
            'SWITCH_LEVER_URL': {'Delivery': '/api/v1/contract_switch_lever_rate',
                                 'Swap': '/swap-api/v1/swap_switch_lever_rate',
                                 'LinearSwap': '/linear-swap-api/v1/swap_switch_lever_rate'},
            'DEFAULT_SYMBOL': {'Delivery': 'ETC',
                               'Swap': 'BTC',
                               'LinearSwap': 'BTC'},
            'DEFAULT_CONTRACT_CODE': {'Delivery': 'ETC_CW',
                                      'Swap': 'ETH-USD',
                                      'LinearSwap': 'BTC-HUSD'},
            'CANCEL_ALL_TRACK_ORDER_URL': {'Delivery': '/api/v1/contract_track_cancelall',
                                           'Swap': '/swap-api/v1/swap_track_cancelall',
                                           'LinearSwap': '/linear-swap-api/v1/swap_track_cancelall'},
            'CANCEL_ALL_TPSL_ORDER_URL': {'Delivery': '/api/v1/contract_tpsl_cancelall',
                                          'Swap': '/swap-api/v1/swap_tpsl_cancelall',
                                          'LinearSwap': '/linear-swap-api/v1/swap_tpsl_cancelall'},
            'CANCEL_ALL_TRIGGER_ORDER_URL': {'Delivery': '/api/v1/contract_trigger_cancelall',
                                             'Swap': '/swap-api/v1/swap_trigger_cancelall',
                                             'LinearSwap': '/linear-swap-api/v1/swap_trigger_cancelall'},
            'POSITION_INFO_URL': {'Delivery': '/api/v1/contract_position_info',
                                  'Swap': '/swap-api/v1/swap_position_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_position_info'},
            'CONTRACT_ORDER': {'Delivery': '/api/v1/contract_order',
                               'Swap': '/swap-api/v1/swap_order',
                               'LinearSwap': '/linear-swap-api/v1/swap_order'},
            'CONTRACT_INFO_URL': {'Delivery': '/api/v1/contract_contract_info',
                                  'Swap': '/swap-api/v1/swap_contract_info',
                                  'LinearSwap': '/linear-swap-api/v1/swap_contract_info'},
            'MARKET_DEPTH_URL': {'Delivery': '/market/depth',
                                 'Swap': '/swap-ex/market/depth',
                                 'LinearSwap': '/linear-swap-ex/market/depth'},
            'WSURL': 'ws://newtest20-contract-hw.dm.huobiapps.com',
            'REDIS_CONF': {'Delivery': {
                "redis6379": {"host": "172.18.6.119", "port": 6379, "pwd": "rNEAz9uFwHoymy5i"},
                "redis7000": {"host": "172.18.6.119", "port": 7000, "pwd": ""},
                "redis7001": {"host": "172.18.6.119", "port": 7001, "pwd": ""},
                "redis7002": {"host": "172.18.6.119", "port": 7002, "pwd": ""},
                "redis6380": {"host": "172.18.6.119", "port": 6380, "pwd": "rNEAz9uFwHoymy5i"}},
                'Swap': '',
                'LinearSwap': ''},
            'MQ_INFO': {'Delivery': '',
                        'Swap': '',
                        'LinearSwap': ''},
            'MYSQL_CONF': {'Delivery': '',
                           'Swap': '',
                           'LinearSwap': ''},
            'USERINFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''},
            'MGT_INFO': {'Delivery': '',
                         'Swap': '',
                         'LinearSwap': ''}
        }
    }

    @classmethod
    def get_global_data(cls, env=None, system_type=None):
        if env and system_type:
            response = {}
            env_paramdic = cls.config_data[env]
            for k, v in env_paramdic.items():
                if 'dict' in str(type(v)):
                    response[k] = v[system_type]
                else:
                    response[k] = v
            return response
        else:
            return False


if __name__ == '__main__':
    # print(GlobalData.get_global_data())
    # print(GlobalData.get_global_data(env='Test6'))
    print(GlobalData.get_global_data(env='Test20', system_type='Delivery'))
